name: Test

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Important for tags and history

    - name: Extract environment from tag
      run: |
        echo "TAG_SUFFIX=$(echo ${GITHUB_REF#refs/tags/v} | cut -d'-' -f2-3)" >> $GITHUB_ENV
        echo "Extracted TAG_SUFFIX=${{ env.TAG_SUFFIX }}"
        
    - name: Check secret for ${{ env.TAG_SUFFIX }}
      run: |
        SECRET_NAME="AZURE_WEBAPP_PUBLISH_PROFILE_${{ env.TAG_SUFFIX }}"
        echo "Checking secret: $SECRET_NAME"
        if [ -n "${{ secrets[format('AZURE_WEBAPP_PUBLISH_PROFILE_{0}', env.TAG_SUFFIX)] }}" ]; then
          echo "Secret exists and is not empty"
          echo "Secret length: ${#SECRET_VALUE}"
        else
          echo "Secret is empty or not found"
          exit 1
        fi
      env:
        SECRET_VALUE: ${{ secrets[format('AZURE_WEBAPP_PUBLISH_PROFILE_{0}', env.TAG_SUFFIX)] }}